version: '3.8'

services:
  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecom-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5001:5001"
      - "5003:5003"
    networks:
      - ecom-network

  # Nginx Reverse Proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: ecom-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
  #   environment:
  #     - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
  #     - AUTH_SERVICE_HOST=app
  #     - AUTH_SERVICE_PORT=5003
  #     - USER_SERVICE_HOST=app
  #     - USER_SERVICE_PORT=5001
  #   depends_on:
  #     - app
  #   networks:
  #     - ecom-network

networks:
  ecom-network:
    driver: bridge