version: '3.8'

services:
  auth:
    image: ${DOCKER_USER}/auth:${TAG:-latest}
    #image: auth
    env_file:
      - ./.env
   # container_name: supacart-gym-api
    ports:
      - "5003:5003"
      - "5004:5004"
    restart: always
    networks:
      - app-network
  user:
    image: ${DOCKER_USER}/user:${TAG:-latest}
    #image: user
    env_file:
      - ./.env
   # container_name: supacart-gym-api
    ports:
      - "5001:5001"
      - "5002:5002"
    restart: always
    networks:
      - app-network

  nginx:
    image: ${DOCKER_USER}/nginx-proxy:${TAG:-latest}
    #image: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    depends_on:
      - auth
      - user
    # restart: always
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email oakarkyaw@gmail.com -d ecommerce-backend.ddns.net --agree-tos --no-eff-email

networks:
  app-network:
    driver: bridge
