version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/conf.d/default.conf
    depends_on:
      - user
      - auth
    networks:
      - ecom

  user:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: user
        APP_PORT: 5001
    container_name: user
    image: oakarkyaw/user:latest
    restart: unless-stopped
    ports:
      - "5001:5001"
    depends_on:
      - user_db
      - redis
    networks:
      - ecom
      - pgnet

  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: auth
        APP_PORT: 5003
    container_name: auth
    image: oakarkyaw/auth:latest
    restart: unless-stopped
    ports:
      - "5003:5003"
    depends_on:
      - auth_db
      - redis
    networks:
      - ecom
      - pgnet

  user_db:
    image: postgres:17
    container_name: user_db
    restart: unless-stopped
    volumes:
      - user_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pgnet

  product_db:
    image: postgres:17
    container_name: product_db
    restart: unless-stopped
    volumes:
      - product_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - pgnet

  auth_db:
    image: postgres:17
    container_name: auth_db
    restart: unless-stopped
    volumes:
      - auth_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - pgnet

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "megasmart123"]
    networks:
      - pgnet

volumes:
  user_data:
  product_data:
  auth_data:
  redis_data:

networks:
  ecom:
    driver: bridge
  pgnet:
    driver: bridge
