version: '3.8'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: user
        APP_PORT: 5001
    container_name: user
    image: ${DOCKER_USERNAME}/user:latest
    restart: unless-stopped
    # env_file:
    #   - .env
    ports:
      - "5001:5001"
    networks:
      - ecom

  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: auth
        APP_PORT: 5003
    container_name: auth
    image: ${DOCKER_USERNAME}/auth:latest
    restart: unless-stopped
    # env_file:
    #   - .env
    ports:
      - "5003:5003"
    networks:
      - ecom

networks:
  ecom:
    driver: bridge