version: '3.8'

services:
  user:
    build:
      context: .                      # Root of monorepo
      dockerfile: apps/user/Dockerfile  # Path from root
    container_name: user
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5001:5001"
    networks:
      - ecom
  auth:
    build:
      context: .                      # Root of monorepo
      dockerfile: apps/auth/Dockerfile  # Path from root
    container_name: auth
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5003:5003"
    networks:
      - ecom

networks:
  ecom:
    driver: bridge