version: "3.8"

services:
  user:
    image: oakarkyaw/user:latest
    container_name: user
    restart: unless-stopped
    env_file: .env
    networks:
      - ecom
    volumes:
      - ./logs/user:/var/log/nestapp  

  product:
    image: oakarkyaw/product:latest
    container_name: product
    restart: unless-stopped
    env_file: .env
    networks:
      - ecom
    volumes:
      - ./logs/product:/var/log/nestapp

  auth:
    image: oakarkyaw/auth:latest
    container_name: auth
    restart: unless-stopped
    env_file: .env
    networks:
      - ecom
    volumes:
      - ./logs/auth:/var/log/nestapp

networks:
  ecom:
    driver: bridge
