name: CICD

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
    types:
      - closed

env:
  REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push services using Docker Compose
        run: |
          # Ensure Docker Compose version 1.29.2 (or higher) is available
          docker --version
          
          # Build and push using docker-compose (for both user and auth services)
          docker compose build --platform linux/amd64
          
          # Push the images to Docker Hub
          docker compose  push

  deploy:
    needs: build
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            set -euo pipefail

            echo "🔹 Pull latest images..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/user:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/auth:latest

            echo "🔹 Stop old containers if running..."
            sudo docker rm -f user_service auth_service || true

            echo "🔹 Run User service..."
            sudo sudo docker run -d \
              --name user_service \
              -p 5001:5001 \
              --env-file /home/ubuntu/megasmart-backend/.env \
              ${{ secrets.DOCKER_USERNAME }}/user:latest

            echo "🔹 Run Auth service..."
            sudo docker run -d \
              --name auth_service \
              -p 5003:5003 \
              --env-file /home/ubuntu/megasmart-backend/.env \
              ${{ secrets.DOCKER_USERNAME }}/auth:latest

            echo "🧹 Clean up old images..."
            docker image prune -af || true

            echo "🎉 Deployment complete!"
